#!/bin/sh

source $(dirname $0)/common.sh

URL=$(cat)

PLUGIN_TAG=master

PLUGIN_NAME=$( basename $URL )

[[ -d ${PLUGIN_DIR}/${PLUGIN_NAME} ]] \
|| mkdir -p ${PLUGIN_DIR}/${PLUGIN_NAME}

cd ${PLUGIN_DIR}/${PLUGIN_NAME}

download $URL/archive/${PLUGIN_TAG}.tar.gz \
| gunzip \
| tar --strip-compontents=1 -x -f -